config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Define the welcome route
  get "play", to: "inputs#play", as: 'game'

  get "score", to: "inputs#score", as: 'user_answer'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def answer
    @user_answer = params[:user_word]
    @random_letters = ('A'..'Z').to_a.sample(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inputs_controller.rb
require 'open-uri'

class InputsController < ApplicationController
  def play
    @random_letters = ('A'..'Z').to_a.sample(9)
    start_time = Time.now
    end_time = Time.now
  end

  def score
    @user_answer = params[:user_word]
    result = URI.open("https://dictionary.lewagon.com/#{@user_answer}").read
    word = JSON.parse(result)
    @random_letters = params[:random_letters].split


    @all_included = @user_answer.chars.all? do |letter|
      @random_letters.include?(letter)
    end
  if word["found"]
    if @all_included
      @score = "Congrats"
    else
      @score = "Your score is zero"
    end
  end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/views/answers/answer.html.erb
    <div class="container mt-5">
        <h1 class="text-center">Welcome to the longest word-game!</h1>
        <p class="text-center">Here is your grid:</p>
        <div class="grid mx-auto" style="max-width: 300px;">
            <div>Q</div>
            <div>F</div>
            <div>M</div>
            <div>R</div>
            <div>K</div>
            <div>L</div>
            <div>I</div>
            <div>T</div>
            <div>P</div>
        </div>
        <p class="text-center">*****************************************************</p>
        <p class="text-center">What is your longest word?</p>
        <form id="word-form" class="text-center">
            <div class="form-group">
                <input type="text" id="user-word" name="user-word" class="form-control d-inline-block w-auto" placeholder="Enter your word" required>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
        <div class="results text-center mt-4">
            <h2>Now your results</h2>
            <p>Your word: <strong id="display-word"><%=  @user_answer %></strong></p>
            <p>Time Taken to answer: <strong id="time-taken">12.07916</strong></p>
            <p>Your score: <strong id="score">3.194722666666667</strong></p>
            <p>Message: <strong id="message">Well Done!</strong></p>
             <%= link_to "Play again", game_url %>
        </div>

app/views/inputs/play.html.erb
    <div class="container mt-5">
        <h1 class="text-center">Welcome to the longest word-game!</h1>
        <p class="text-center">Here is your grid:</p>
        <div class="grid mx-auto" style="max-width: 300px;">

        <% @random_letters.each do |letter| %>
        <div><%= letter %></div>
        <% end %>
        </div>
        <p class="text-center">*****************************************************</p>
        <p class="text-center">What is your longest word?</p>
        <form id="word-form" class="text-center" action="/score" data-turbo="false" >
            <div class="form-group" >
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <%= hidden_field_tag :random_letters, @random_letters %>

                <input type="text" id="user-word" name="user_word" class="form-control d-inline-block w-auto" placeholder="Enter your word" required>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>

app/views/inputs/score.html.erb
    <div class="container mt-5">
        <h1 class="text-center">Welcome to the longest word-game!</h1>
        <p class="text-center">Here is your grid:</p>
        <div class="grid mx-auto" style="max-width: 300px;">

        <% @random_letters.each do |letter| %>
        <div><%= letter %></div>
        <% end %>
        </div>
        <p class="text-center">*****************************************************</p>
        <p class="text-center">What is your longest word?</p>
        <form id="word-form" class="text-center" action="/score" data-turbo="false" >
            <div class="form-group" >
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <%= hidden_field_tag :random_letters, @random_letters %>

                <input type="text" id="user-word" name="user_word" class="form-control d-inline-block w-auto" placeholder="Enter your word" required>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
        <div><%= @score %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>